
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FROM = 73;
  public static final int LITERALNULL = 83;
  public static final int BITNOT = 38;
  public static final int CORCHETEDER = 7;
  public static final int RAISE = 76;
  public static final int POTENCIA = 19;
  public static final int LAMBDA = 78;
  public static final int MAYOR = 39;
  public static final int PASS = 75;
  public static final int DIFERENTE = 22;
  public static final int ELIF = 46;
  public static final int DISTINTO = 23;
  public static final int DEL = 72;
  public static final int SHR = 34;
  public static final int NOT = 55;
  public static final int DEF = 45;
  public static final int SHL = 33;
  public static final int ERROR = 71;
  public static final int FLOAT = 63;
  public static final int IGUALCOMP = 21;
  public static final int EOFINAL = 84;
  public static final int MOD = 18;
  public static final int CLASS = 43;
  public static final int EXCEPT = 48;
  public static final int COMA = 8;
  public static final int LITERALINT = 67;
  public static final int TAB = 3;
  public static final int EXEC = 81;
  public static final int WHILE = 60;
  public static final int CHAR = 66;
  public static final int BOOLEAN = 65;
  public static final int DOSPUNTOS = 10;
  public static final int PARENTESISDER = 5;
  public static final int PUNTOYCOMA = 11;
  public static final int INPUT = 53;
  public static final int CORCHETEIZQ = 6;
  public static final int FOR = 50;
  public static final int LITERALFALSE = 74;
  public static final int DIV = 16;
  public static final int RETURN = 58;
  public static final int MULT = 15;
  public static final int BITOR = 36;
  public static final int ELSE = 47;
  public static final int TRY = 59;
  public static final int MENOS = 14;
  public static final int MENOR = 40;
  public static final int LITERALFLOAT = 68;
  public static final int MAS = 13;
  public static final int BREAK = 42;
  public static final int INT = 61;
  public static final int DIVIGUAL = 29;
  public static final int DIVENTIGUAL = 31;
  public static final int EOF = 0;
  public static final int PUNTO = 9;
  public static final int PRINT = 57;
  public static final int CAMBIOLINEA = 12;
  public static final int IMPORT = 79;
  public static final int MENORIGUAL = 25;
  public static final int IS = 54;
  public static final int LITERALSTRING = 69;
  public static final int IN = 52;
  public static final int BITAND = 35;
  public static final int OR = 56;
  public static final int error = 1;
  public static final int FINALLY = 49;
  public static final int MASIGUAL = 26;
  public static final int CONTINUE = 44;
  public static final int LIST = 62;
  public static final int IF = 51;
  public static final int BITXOR = 37;
  public static final int ID = 2;
  public static final int ASSERT = 77;
  public static final int MULTIGUAL = 28;
  public static final int MENOSIGUAL = 27;
  public static final int POTIGUAL = 30;
  public static final int GLOBAL = 80;
  public static final int ASIGNACION = 20;
  public static final int MAYORIGUAL = 24;
  public static final int LITERALTRUE = 82;
  public static final int MODIGUAL = 32;
  public static final int DIVENT = 17;
  public static final int RANGE = 85;
  public static final int STRING = 64;
  public static final int LITERALCHAR = 70;
  public static final int AND = 41;
  public static final int PARENTESISIZQ = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "TAB",
  "PARENTESISIZQ",
  "PARENTESISDER",
  "CORCHETEIZQ",
  "CORCHETEDER",
  "COMA",
  "PUNTO",
  "DOSPUNTOS",
  "PUNTOYCOMA",
  "CAMBIOLINEA",
  "MAS",
  "MENOS",
  "MULT",
  "DIV",
  "DIVENT",
  "MOD",
  "POTENCIA",
  "ASIGNACION",
  "IGUALCOMP",
  "DIFERENTE",
  "DISTINTO",
  "MAYORIGUAL",
  "MENORIGUAL",
  "MASIGUAL",
  "MENOSIGUAL",
  "MULTIGUAL",
  "DIVIGUAL",
  "POTIGUAL",
  "DIVENTIGUAL",
  "MODIGUAL",
  "SHL",
  "SHR",
  "BITAND",
  "BITOR",
  "BITXOR",
  "BITNOT",
  "MAYOR",
  "MENOR",
  "AND",
  "BREAK",
  "CLASS",
  "CONTINUE",
  "DEF",
  "ELIF",
  "ELSE",
  "EXCEPT",
  "FINALLY",
  "FOR",
  "IF",
  "IN",
  "INPUT",
  "IS",
  "NOT",
  "OR",
  "PRINT",
  "RETURN",
  "TRY",
  "WHILE",
  "INT",
  "LIST",
  "FLOAT",
  "STRING",
  "BOOLEAN",
  "CHAR",
  "LITERALINT",
  "LITERALFLOAT",
  "LITERALSTRING",
  "LITERALCHAR",
  "ERROR",
  "DEL",
  "FROM",
  "LITERALFALSE",
  "PASS",
  "RAISE",
  "ASSERT",
  "LAMBDA",
  "IMPORT",
  "GLOBAL",
  "EXEC",
  "LITERALTRUE",
  "LITERALNULL",
  "EOFINAL",
  "RANGE"
  };
}

